FROM openjdk:8

ADD https://downloads.apache.org//ant/binaries/apache-ant-1.10.11-bin.tar.gz /root/ant.tar.gz
COPY . /build
WORKDIR /build

RUN tar -xzvf /root/ant.tar.gz && \
            mv apache-ant* /ant && \
            /ant/bin/ant download-deps && \
            /ant/bin/ant

VOLUME [ "/build" ]

ENTRYPOINT [ "/ant/bin/ant" ]
